### ISSUE TITLE
test_environment fails for python 2.6,2.7,3.2,3.3

### ISSUE THREAD

**Issue by jlec** [amoffat/sh#178]
# 
## FAIL: test_environment (**main**.FunctionalTests)

Traceback (most recent call last):
  File "test.py", line 264, in test_environment
    self.assertEqual(out, "DERP 1")
AssertionError: u'DERP 2' != 'DERP 1'

---

**Comment by jlec** [comment]
Still present in the 1.11 release

**Comment by amoffat** [comment]
@jlec would you mind debugging this in your environment?  here's [the relevant line.](https://github.com/amoffat/sh/blob/master/test.py#L292)  basically python on OSX adds a bunch of environment variables to an otherwise clean environment.  it mucks with the test to confirm that sh only adds a single name to a subprocess's environment, and the value of that name

**Comment by lopsided98** [comment]
I am running into this issue with Python 3.7 using [Nix](https://nixos.org/nix/), although the cause is probably different from the original report.

Python 3.7 is defining `LC_CTYPE=C.UTF-8` due to [PEP 538](https://www.python.org/dev/peps/pep-0538/).

Running `env -i $(nix-build '<nixpkgs>' -A python37)/bin/python -c 'import os; print(os.environ)'` prints:
```
environ({'LC_CTYPE': 'C.UTF-8'})
```
while `env -i $(nix-build '<nixpkgs>' -A python36)/bin/python -c 'import os; print(os.environ)'` prints:
```
environ({})
```

`env -i PYTHONCOERCECLOCALE=warn  $(nix-build '<nixpkgs>' -A python37)/bin/python -c 'import os; print(os.environ)'` prints:
```
Python detected LC_CTYPE=C: LC_CTYPE coerced to C.UTF-8 (set another locale or PYTHONCOERCECLOCALE=0 to disable this locale coercion behavior).
environ({'PYTHONCOERCECLOCALE': 'warn', 'LC_CTYPE': 'C.UTF-8'})
```
This shows that the `LC_TYPE` definition is definitely caused by PEP 538.

It seems like it makes sense to ignore `LC_TYPE` in order to be compatible with Python 3.7.

Interestingly, I did some tests with Arch Linux and it has different behavior. Running `env -i PYTHONCOERCECLOCALE=warn python3.7 -c 'import os; print(os.environ)'` prints:
```
Python runtime initialized with LC_CTYPE=C (a locale with default ASCII encoding), which may cause Unicode compatibility problems. Using C.UTF-8, C.utf8, or UTF-8 (if available) as alternative Unicode-compatible locales is recommended.
environ({'PYTHONCOERCECLOCALE': 'warn'})
```
This seems like it must be caused by some difference in how they are configured/compiled, but I can't find any specific explanation.

**Comment by lopsided98** [comment]
Here is more succinct documentation of the final implementation: https://docs.python.org/3/using/cmdline.html#envvar-PYTHONCOERCECLOCALE

**Comment by amoffat** [comment]
202c28fb fixes this by making environment testing more robust.
