### ISSUE TITLE
`which` should take an optional parameter...the paths to search

### ISSUE THREAD

**Issue by amoffat** [amoffat/sh#226]
and `Command` should be able to take an optional list of paths to manually search for the program, which get passed to `which`

**Comment by mandarvaze** [comment]
Should this optional parameter take precedence over default search path ?
e.g. If I have "ls" in "/my/home/dir" - which "ls" should ``which`` return ? ("/bin/ls" or "/my/home/dir/ls")

    import sh
    sh.which("ls", "/my/home/dir")

I think it should return ``/my/home/dir/ls`` otherwise user would not have passed additional argument

Also, I assume that optional path would be a list, right ?

**Comment by amoffat** [comment]
You've got it right @mandarvaze 

The idea I was going for was [the constructor](https://github.com/amoffat/sh/blob/master/sh.py#L785) would take an optional param for paths that defaults to `None`.  If it's `None`, the paths are constructed to be either an empty list (in the case of "PATH" not in `os.environ`) or the list of your runtime paths: https://github.com/amoffat/sh/blob/master/sh.py#L311-L313, which would then be passed into `which` (and the existing logic in `which` refactored out)

It's not super complex but would allow people to override where their programs are searched for without needing to modify their `PATH`
