### ISSUE TITLE
Restore 1.09 logging_enabled check?

### ISSUE THREAD

**Issue by asoc** [amoffat/sh#244]
First off, awesome library.

Now, I have a project that uses the `logging` library itself, and while I could add code to turn off 'sh' logging I'd have to do it in a *lot* of places due to the project layout. Right now I get `[INFO] sh.command <Command '...'> starting process` littered about everywhere, including when I run shell scripts.

Any chance you can turn off all logging by default as before, or at least change the level to `DEBUG` since it's more debugging information than anything else? 

Thanks,
 \- Alex

**Comment by amoffat** [comment]
Hi Alex.  You can change the logging level of a logger by its namespace.  Take a look at [this](http://stackoverflow.com/a/11029841) answer.  This is probably the easiest way.  There is also a way to completely disable logging for a namespace, but it is a little more involved:

```python
logger = logging.getLogger("sh")
logger.propagate = False
logger.addHandler(logging.NullHandler())
```

Let me know if this works

**Comment by asoc** [comment]
The problem with that approach is as I said, I have a lot of entry points so I'd have to add that code in a lot of places. 

Maybe I can word it this way:
Any reason why [this line](https://github.com/amoffat/sh/blob/master/sh.py#L481) is `info` instead of `debug` like it is [here](https://github.com/amoffat/sh/blob/master/sh.py#L1351), or even why that first one exists since you're debugging the same message in the `OProc.__init__`?

**Comment by amoffat** [comment]
Yes, `OProc` is much lower level than `Command`, so it gets the debug level.  I don't think you should depend on a package's logging levels being static.  Your best bet is to handle sh's logging propagation where you set up your logging.  This is pretty standard for a 3rd party packge.  Having a `logging_enabled` flag is pretty non-standard, which is why it was removed.  If you are setting up logging in many entry points in your project, then you will also need to add the filtering/disabling code in all of those entry points, or refactor it so you only need to do it in one place.

**Comment by asoc** [comment]
I agree that 3rd party packages likely have configurable logging, but most libraries I've used are either use logging because it's part of the library's purpose (such as django, cherrypy, where logging is expected), only have debugging output with verbosity flags (pexpect, telnetlib), or have specific places they pipe debug output to instead of to `stdout`.

Having "starting process" print out is not useful in most situations.

I'll close this anyway since I don't think I'm gonna get my way :)

Cheers,
 - Alex
