### ISSUE TITLE
Add _print option to send output to console

### ISSUE THREAD

**Issue by noisygecko** [amoffat/sh#246]
It would be great to have an option to print the output from commands as they execute. I am thinking something that would replace

```
for line in sh.tar('xvf', 'stuff.tgz', _iter=True):
    print line,
```

with this

```sh.tar('xvf', 'stuff.tgz', _print=True)```

It sounds like implementing the _fg option would handle this as well, but that is much more complicated than what I envision for the _print option, since it only handles what is done with the output.

**Comment by JohnLunzer** [comment]
While I do support something like this for the sake of simplicity. If you truly don't like the iterator syntax (which I don't) It's easy to provide a printer function yourself to ``_out`` such that:

``` python
def printer(line):
    print(line)

sh.tar('xvf', 'stuff.tgz', _out=printer)
```

Then ``printer`` can be used throughout your program rather than having ugly iterators everywhere. This can be seen in the documentation [here, they are called callbacks](https://amoffat.github.io/sh/#stdout-err-callbacks).

Callbacks for sh are actually extremely powerful.

**Comment by Lucas-C** [comment]
You can also use the following:
```
import sh, sys
sh.tar('xvf', 'stuff.tgz', _out=sys.stdout)
```
