### ISSUE TITLE
Using mysqld_multi via sh kills mysqladmin grandchildren with SIGHUP before they have a chance to do anything

### ISSUE THREAD

**Issue by hoelzro** [amoffat/sh#266]
I found this issue when writing a MySQL helper script that uses `mysqld_multi`.  The problematic line looks like this:

    sh.mysqld_multi('stop', '1')

`mysqld_multi` is an interesting script that forks off a `mysqladmin` process for each start/stop action, but doesn't wait for them to finish before exiting itself.  As a result, the controlling terminal that `sh` creates for `mysqld_multi` (which is the controlling terminal for its `mysqladmin` children) is closed when `sh` cleans up after invoking `mysqld_multi`, and the `mysqladmin` grandchildren processes are sent a `SIGHUP` by the kernel.

Here is a script that reproduces the behavior without involving MySQL scripts:

```python
import sh
from tempfile import NamedTemporaryFile
from textwrap import dedent
import time

with \
    NamedTemporaryFile() as output_file, \
    NamedTemporaryFile() as child_file, \
    NamedTemporaryFile() as parent_file:

    child_file.write(dedent('''
    import signal
    import sys
    import time

    with open({output_file}, 'w') as f:
        def handle_sighup(signum, frame):
            f.write('got signal %d' % signum)
            sys.exit(signum)
        signal.signal(signal.SIGHUP, handle_sighup)
        time.sleep(5)
        f.write('made it!\\n')
    '''.format(output_file=repr(output_file.name))))
    child_file.flush()

    parent_file.write(dedent('''
    import os
    import time

    os.spawnlp(os.P_NOWAIT, 'python', 'python', {child_file})
    time.sleep(2) # give child a chance to set up
    '''.format(child_file=repr(child_file.name))))

    parent_file.flush()

    sh.python(parent_file.name)
    time.sleep(10)

    print output_file.readlines()[0] # should print 'made it'
```

**Comment by amoffat** [comment]
After a lot of reading, I *think* the right move here is to only give an sh subprocess a controlling terminal IFF we are using `_tty_in=True` (which is `False` by default).  My rationale is that if a process doesn't have a tty for stdin, then it doesn't make sense for it to have a controlling terminal (because, how could you send signals from the controlling terminal if you cannot input through a tty).  This solves grandchild processes from receiving SIGHUP (because there is no ctty that hangs up).  Additonally, if you do choose to launch a process with `_tty_in=True`, then you're launching the process as if it were a shell, so any subprocesses launched within that shell should receive SIGHUP, just like if they were launched in the foreground from a shell, and the shell hangs up.

https://github.com/amoffat/sh/commit/e1d2a2c97330dda1f596aed532d81ad1e79de9db

this will go out with the `release-1.2` release.  interested if you have any additional thoughts
