### ISSUE TITLE
Options before arguments

### ISSUE THREAD

**Issue by goerz** [amoffat/sh#324]
Many command line tools require that options come before arguments. When giving options in `sh` via keyword arguments, there does not seem to be any way (something like `_options_first=True`) to make sure that the program is called correctly. Of course, it is still possible to give the options to `sh` in their string form, but that isn't very nice.

Basically, I would like something like

    from sh import ls
    ls('/', l=True, _options_first=True)

to execute `ls -l /` insead of `ls / -l`. I don't want to have to resort to `ls('-l', '/')`

**Comment by amoffat** [comment]
I think `_options_first` is a very specific option...I'm thinking maybe too specific.  It also wouldn't handle interleaving positional and keyword arguments, something that somebody would eventually request.

I see the usefulness of specifying an argument easily programmatically, and it is indeed easier to specify a argument with a keyword argument than it is a string, but I don't think that alone warrants a new specific option.

I do think this plays into another feature though I've been thinking about for the past year, so thank you for bringing it up.

**Comment by bburky** [comment]
Can you please consider reopening this issue? 

There is a common pattern that many shell commands support to safely allow passing positional arguments that may contain a leading hyphen. The following command deletes a file named `-rf` and does _not_ interpret it as a command line argument:
```
rm -- -rf
```

If sh supported `_options_first` I could do either:
```python
from sh import rm
untrusted_input = "-rm"
rm('--', untrusted_input, _options_first=True)

# or with bake:
safe_rm = rm.bake('--', untrusted_input)
safe_rm(untrusted_input)

# I think this is the only way to safely pass arguments like this today:
def safe_rm(*args, **kwargs)
    return rm.bake(**kwargs).bake('--')(*args)
```

Without something like `_options_first` it is not possible to safely pass untrusted arguments to many shell commands.

Adding #53 for reference too, which is similar.

**Comment by amoffat** [comment]
Hi @bburky 

Why doesn't `rm('--', '-rf')` work correctly as-is?

**Comment by bburky** [comment]
Rm is just an example. Realistically I would want to pass some additional parameters using sh's kwargs support. I cannot currently easily do this if I want to use a `--` parameter before my positional args with them at the end.

**Comment by amoffat** [comment]
Oh I see.. right, if you wanted additional args to `rm`, yes they could not be keyword arguments. Looking back at my comment from 2016, I think I still agree with my position. If there was an `_options_first` special arg, it doesn't handle interleaving some kwargs before args, and some kwargs after args. So I don't like it as a general solution to the problem.

I think if you want fine grained control, including the special case of "all kwargs before args", your best bet is still to use `.bake()` to bake the exact order that you want, or use the string version (instead of the kwarg version) and order them as needed. It's clunky, but the problem is also clunky. A wrapper like you wrote with `safe_rm` is a totally valid way to call more complicated `sh` functions as well.
