### ISSUE TITLE
Is there a way I can suppress a bg command exception that happens after I wait()?

### ISSUE THREAD

**Issue by scottbelden** [amoffat/sh#349]
If I bg a command that throws an exception and eventually call `wait()` on it, is there a way to handle/suppress the exception that gets put in the queue? From this comment (https://github.com/amoffat/sh/blob/master/sh.py#L2278-L2284) and my experience, it seems like I can't. However, what this means is that when I do call `wait` on it, if I try to ignore the exception then the one in the queue still gets shown, and if I eventually want to raise or print the exception, it looks like it gets done twice (one that I handle and the one placed in the queue).

For example:

```python
from __future__ import print_function
import sh

# This try block will still show the exception that I want to ignore
try:
    rc = sh.ls('asdfasdf', _bg=True)
    print('calling wait...')
    rc.wait()
except:
    print('no file')

# This try block will cause the exception to be shown twice
try:
    rc = sh.ls('asdfasdf', _bg=True)
    print('calling wait...')
    rc.wait()
except:
    raise
```

I saw https://github.com/amoffat/sh/blob/master/sh.py#L2055-L2062, but unless I'm using it wrong, it doesn't seem like I'm able to use that to swallow the exception before it automatically gets printed.

Ideally I'd like to be able to start the command with `_bg=True` and tell it not to show exceptions if they happen (because I plan to eventually call `wait`), but at a minimum I would expect that if I call `wait` and the exception hasn't happened that it act more similarly to as if I just ran the command without `_bg=True`.

Please let me know if there already exists a way to do what I'm trying to do. If not, would you be open to making the change or accepting a PR that does?

**Comment by amoffat** [comment]
I believe I added `bg_thread_exc` for debugging the sh internal threads, so that's not something you can use.

I don't think sh can do want you want to right now.  Exceptions raised in a background `RunningCommand` are indeed uncaught, so it is correct to propagate them.  But I also understand that there is no way to catch them, even if you wanted to.  So I can see how it can be annoying to see an exception twice, if you are also calling `.wait()` later on.

I would merge a PR that added a new special keyword argument `_bg_exc` that defaults to `True`.  It looks like you could check for its value here https://github.com/amoffat/sh/blob/master/sh.py#L1987.  You can probably skip adding a test for the behavior, since we skip the entire branch that raises background exceptions anyways.  You'll also need a small PR for the docs on `gh-pages` branch to update http://amoffat.github.io/sh/sections/special_arguments.html with the new kwarg.
