### ISSUE TITLE
Access _env once baked

### ISSUE THREAD

**Issue by retr0h** [amoffat/sh#382]
I bake a command and pass it to a utility which executes it.  How can I access the environment a command was baked with prior to execution?

```
>>> ls = sh.ls.bake(_env=os.environ)
>>> ls._env
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jodewey/.pyenv/versions/molecule2-env-2.7.13/lib/python2.7/site-packages/sh.py", line 1219, in __getattribute__
    val = getattr(name)
AttributeError: 'Command' object has no attribute '_env'
```

**Comment by amoffat** [comment]
Short answer: you can't

Longer answer: `cmd._partial_call_args["env"]`, but you should not rely on it, since that private attribute will likely change in the future and it will break your code

Longest answer: if a function needs to know the environment of the command passed to it, you are better off passing the environment into the function along with the command, rather than trying to dig it out of the function.

**Comment by retr0h** [comment]
Thanks @amoffat
