### ISSUE TITLE
ctrl-c does not propagate

### ISSUE THREAD

**Issue by esc** [amoffat/sh#389]
When I run `wget` or `tar` through `sh` and hit `Ctrl-C` the underlying processes aren't terminated. Is this correct? Is this intended behaviour? Currently I am using `atexit` to explicitly `kill` the process.

**Comment by esc** [comment]
But of course, this doesn't work with `multiprocessing`.

**Comment by amoffat** [comment]
Your Python script is what receives a SIGINT, not the processes launched from python, because Python is the foreground process of your controlling terminal.  Python then transforms a SIGINT into a KeyboardInterrupt.  It's up to you to catch a KeyboardInterrupt and respond accordingly.

Alternatively, you may use `_fg=True` which puts the spawned process in the foreground session group of the controlling terminal, allowing it access to signals and controlling terminal IO.  You can't use most other special options with `_fg=True` though, so it may not be for you.

**Comment by amoffat** [comment]
Really it just comes down expectations and how that fits into the unix process model.  Half of sh users expect a process to die when the script dies, the other half expect a process to live beyond the script :)  It is really the unix process model, and my attempt at sensible defaults, that guide what makes the most sense.

Maybe this topic warrants an FAQ entry?  There isn't one now, but I imagine you did look there first to try to solve the problem?

**Comment by amoffat** [comment]
Please re-open the issue if you have additional thoughts
