### ISSUE TITLE
problem executing gpg

### ISSUE THREAD

**Issue by tkossak** [amoffat/sh#395]
I'm having troubles translating this bash one liner
`echo "1234" | gpg --no-use-agent -o /dev/null --local-user MY_KEY -as - && echo "PASSW IS CORRECT"`
(checking if gpg key has password) into sh. I tried:
```
x = sh.gpg('--no-use-agent', '-as', o='/dev/null', local_user='MY_KEY', _fg=True, _in='1234\n')
if x.exit_code == 0:
    print('OK')
else:
    print('NOT OK')
```

But to no avail: when I enter correct gpg password, the last line "Enter passphrase: " disapears and the script is stuck on first line, never printing OK or NOT OK.
I would expect that after entering correct password it would print ok/not ok just like bash one liner.

**Comment by amoffat** [comment]
@tkossak I tried your example and could reproduce it.  This looks like it's related to `_fg=True` and `_in='1234\n`.  After you enter the password, type anything else, then hit control-D (for EOF) and you should get output.  This suggests that `_in` isn't being used.  And that makes sense.  When `_fg=True` is used, the current terminal is attached to the process, so there's no way we can programmatically use `_in` to enter input.  The bug here is that you didn't get an error saying "don't use _fg=True and _in at the same time."

But I know that doesn't help what you're trying to do :)  I think your best bet would be to use a `NamedTemporaryFile` in place of trying to pipe in from stdin:

```python
from tempfile import NamedTemporaryFile
h = NamedTemporaryFile()
sh.gpg('--no-use-agent', '-as', '-o', '/dev/null', '--local-user', 'MY_KEY', h.name, _fg=True)
h.close()
```

**Comment by tkossak** [comment]
This works perfectly, thank you! Even more thank you for this awesome library that i discovered recently! I really like it :)

**Comment by amoffat** [comment]
Happy to help @tkossak!  I'll leave this issue open until I add an exception that makes those two options incompatible
