### ISSUE TITLE
when multiple _bg processes are running, sh blocks randomly when inspecting exited processes

### ISSUE THREAD

**Issue by computercolin** [amoffat/sh#413]
To demonstrate the issue, the following script creates 11 _sleep_ processes and monitors them, starting new processes when old ones exit.

- Expectation: There are 11 processes running at any one time
- Expectation: The script prints status message every 0.5 seconds
- Actual Result: script blocks randomly
    - status output halts
    - script continues to block until process #x exits, and then continues as if nothing happened

Sh blocks because of the implicit call to ```__eq__``` by ```list.remove```. The calls are:
``` __eq__ -> __str__ -> __unicode__ -> self.stdout -> self.wait -> self.process.wait -> no_interrupt```

Why this gets stuck, I do not understand.

Reproduced on Macos python 2.7, 3.4, 3.5

Demo (bit long, try running it, the bug appears within a few minutes for me and is very obvious because the terminal output halts while Sh blocks)
``` python
import random
import sh
import time

MAX_NUM_PROCS = 11
SLEEP_INT_SEC = .5

def mark_exited(p, success, exit_code):
  p.exited = True

def sjoin(glue, itrr):
  return str(glue).join(map(str, itrr))

def process_finished_procs(running_proc_list):
  for p in running_proc_list:
    if not p.exited:
      continue
    isalive, excode = p.process.is_alive()
    x = ['pid:', p.process.pid, '"exited":', p.exited, 'is_alive:', isalive, 'exit_code:', excode]
    print('! Proc complete:: ' + sjoin(' ',x) + ' --- ' + str(p.process.cmd))

    p.wait()
    # BUG OCCURS HERE. When other bg processes are running, call to wait() randomly blocks.
    # wait() will block until bg processes #x have exited (can't see pattern with which #x we get hung on).
    # I discovered the bug with the following list. In fact, if you delete the wait() line
    # the bug will still occur because list.remove() calls __eq__ which ends up calling wait()
    running_proc_list.remove(p)

def wait_n_cull_procs(running_proc_list):
  while len(running_proc_list) >= MAX_NUM_PROCS:
    time.sleep(SLEEP_INT_SEC)
    stars = '*' * random.randint(2,6)
    print('.. running count is %s/%s  %s' % (len(running_proc_list),MAX_NUM_PROCS,stars) )
    process_finished_procs(running_proc_list)

running_proc_list = []
while True:
  wait_n_cull_procs(running_proc_list)
  print('start proc')
  cmd = 'sleep %s; echo "done1234"' % random.randint(200,900)
  p = sh.sh('-c', cmd, _bg=True, _done=mark_exited)
  p.exited = False
  running_proc_list.append(p)
```

**Comment by computercolin** [comment]
To further capture the issue, see how many sleep processes are running. Run the following:

```bash
while True; do ps aux | grep don[e]1234 | wc -l; sleep 4; done
```

Similar to main script, you will see 11 processes, then that number will decrease as Sh gets stuck and blocks.

(script above generates processes that ```echo done1234``` so we can identify them)

**Comment by computercolin** [comment]
I have reproduced the bug in Ubuntu 16.04.3 with python 3.5.2 (... have not tested other python versions yet).
So it appears this is not a MacOS specific bug.

**Comment by amoffat** [comment]
This is a puzzler.  I was able to confirm it and am looking into it now.

**Comment by amoffat** [comment]
A clue... I was able to strace one of the sleep processes as it was hanging and this is what I saw:

```
strace: Process 32299 attached
wait4(-1,

... HANGS ...

[{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 32300
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=32300, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
rt_sigreturn({mask=[]})                 = 32300
exit_group(0)                           = ?
+++ exited with 0 +++
```
It appears that the sh process (not my sh...the shell sh) is waiting for one of it's children to exit (`wait4(-1` means wait for any child proc to terminate). Then a long time later it is reaped. Not much to go on, but that is where its hanging...

**Comment by amoffat** [comment]
I think I get what's happening, and it doesn't appear to be a bug with sh. The clue is basically what you said about `__eq__` calling `.wait()`: `list.remove(p)` is calling `RunningCommand.wait()` *on potentially every process in the list* as it does its linear search for the process to remove. This hangs while each element in the list, in sequence, finishes sleeping, while `.remove()` searches for the process.

Consider the following 4 sleep processes in a list: A, B, C, D, each with the sleep times 1, 7, 2, 5, respectively:

```
+----+----+----+----+
| A1 | B7 | C2 | D5 |
+----+----+----+----+
```
A finishes first, since it only is sleeping for 1 second.  When `process_finished_procs` goes to remove it from the list, it starts at index 0, calls `p.wait()` on the process to do `__eq__` and finds it it immediately -- no hang. Now we look like this (we'll ignore adding new processes for now):

```
+----+----+----+
| B7 | C2 | D5 |
+----+----+----+
```

Then C finishes next after 2 seconds. But when `process_finished_procs` goes to remove it from the list, it sees process B first and calls `p.wait()` on it in order to do `__eq__`, resulting in a hang for 7 seconds. Then it advances to index 1, `p.wait()`, and finds C.

That's basically it. You can make it not hang by adding a `p.idx` field to each process (similarly to how you did `p.exited`) and instead of doing `list.remove(p)`, do `list.pop(p.idx)`.  No more hanging.
