### ISSUE TITLE
Using wildcards

### ISSUE THREAD

**Issue by mschier** [amoffat/sh#425]
I might have missed it somewhere, but is it right that I can't use wildcards in the arguments?
if I runs something like `sh.cd('*')` I get an error like this `FileNotFoundError: [Errno 2] No such file or directory: '*'`, where I would expect to get an error along the lines of `bash: cd: too many arguments`.
Am I not escaping it right or something?

`

**Comment by amoffat** [comment]
https://amoffat.github.io/sh/sections/faq.html#why-doesn-t-work-as-a-command-argument

**Comment by mschier** [comment]
Thanks a lot, I totally missed it :)

**Comment by marto1** [comment]
Just pasting the answer since the link is dead:

### Why doesn’t “*” work as a command argument?

Glob expansion is a feature of a shell, like Bash, and is performed by the shell before passing the results to the program to be exec’d. Because sh is not a shell, but rather tool to execute programs directly, we do not handle glob expansion like a shell would.

So in order to use "*" like you would on the command line, pass it into glob.glob() first:

```
import sh
import glob
sh.ls(glob.glob("*.py")) 
```
