### ISSUE TITLE
Sub processes continue running after KeyboardInterrupt

### ISSUE THREAD

**Issue by danijar** [amoffat/sh#428]
This can be reproduced with any shell command that returns output after a while. Run this script and immediately kill it with <kbd>Ctrl</kbd>+<kbd>C</kbd>.

```py
# sh_keyboard_interrupt.py
import sys, sh
sh.Command('time')('sleep', 5, _out=sys.stdout, _err=sys.stderr)
```

The Python interpreter prints the exception and terminates so the new shell prompt `$` shows up. A few seconds later, the `time` command finishes and prints its result into that line.

```
$ python sh_keyboard_interrupt.py
^CTraceback (most recent call last):
  File "script/sh_keyboard_interrupt.py", line 2, in <module>
    sh.Command('time')('sleep', 5, _out=sys.stdout, _err=sys.stderr)
  File "/usr/local/google/home/danijar/.local/lib/python2.7/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/google/home/danijar/.local/lib/python2.7/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/local/google/home/danijar/.local/lib/python2.7/site-packages/sh.py", line 784, in wait
    exit_code = self.process.wait()
  File "/usr/local/google/home/danijar/.local/lib/python2.7/site-packages/sh.py", line 2358, in wait
    pid, exit_code = no_interrupt(os.waitpid, self.pid, 0) # blocks
  File "/usr/local/google/home/danijar/.local/lib/python2.7/site-packages/sh.py", line 1666, in no_interrupt
    ret = syscall(*args, **kwargs)
KeyboardInterrupt
$ 0.00user 0.00system 0:05.00elapsed 0%CPU (0avgtext+0avgdata 1808maxresident)k
0inputs+0outputs (0major+89minor)pagefaults 0swaps
```

I would like the `KeyboardException` to also kill all running sub processes. Is this expected behavior and is there a way around this?

I'm on Ubuntu 16 with Zsh and I replicated this with Python 2/3.5/3.6.

**Comment by amoffat** [comment]
I believe this is expected behavior.  Processes are forked off in the background, and there's no atexit handlers to clean them up for you if your script exits before the forked process is done.

You have two options.  You can catch `KeyboardException` and clean up any processes yourself (maybe you could use https://docs.python.org/2/library/atexit.html instead).  The other option is, you can launch the process with `_fg=True` and remove `_out=sys.stdout` and `_err=sys.stderr`.  If you just want the output printed to the console, this is the recommended way of doing it (rather than redirecting _err and _out).  What foreground does is enables the launched process to have control of stdout and stderr, as well as receive all signals.  So ctrl+c will be caught by your process (and not python), terminating it.

**Comment by danijar** [comment]
Thanks. How would I stop the running process?

**Comment by amoffat** [comment]
https://amoffat.github.io/sh/sections/command_class.html#RunningCommand.kill

**Comment by danijar** [comment]
Thanks for your help!

**Comment by danijar** [comment]
@amoffat Follow up question: You said that `_fg=True` causes Ctrl+C to be caught by the process I've launched with sh.py. Is there a way to automatically raise an error in Python when that happens, e.g. because the exit code is not zero?
