### ISSUE TITLE
calling a command with a dash in the name via sudo

### ISSUE THREAD

**Issue by carlwgeorge** [amoffat/sh#437]
I'm working on a script that will call the command `yum-builddep`.  When running the entire script as root, it works as documented with an underscore.

```
sh.yum_builddep('--assumeyes', srpm_file)
```

I would like to run this script as a non-root user that has password-less sudo permissions.  I thought this would work:

```
sh.sudo.yum_builddep('--assumeyes', srpm_file)
```

But instead, I get an error that the command `yum_builddep` is not found.  Would it be possible to implement the underscore to dash logic on commands passed to sudo?

I think this may be related to #230, but it's not really about dashes in subcommands, so I decided to go with a new issue.

**Comment by amoffat** [comment]
You're right on it being related to #230.  The problem here is that "yum_builddep" is actually a subcommand to sudo, in the same way that "rev_list" is a subcommand to "git".  So unfortunately you will not get the nice syntax sugar of dashes/underscores in this scenario, and will have to call yum_builddep in a more explicit way, e.g. `sh.sudo("yum-builddep", "--assumeyes", srpm_file)`

**Comment by carlwgeorge** [comment]
That's what I decided to go with in https://github.com/iusrepo/drone-rpmbuild/commit/9b2bd1320566f1d91b23e90d5dac429c709efbf6.  Eventually it the issue will go away, because `yum-builddep` has been replaced by a proper subcommand in dnf, i.e. `dnf builddep`.  Thanks for confirming the best way to handle it for now!
