### ISSUE TITLE
sh.bake rsync exclusion masks vs subprocess.Popen

### ISSUE THREAD

**Issue by michael-will** [amoffat/sh#465]
For some reason running the equivalent of 
/usr/bin/rsync -rptlog --size-only -ansv --include='*/' --include='**/*.arb' --exclude='*' src/ dest2/  
through cmd=sh.rsync.bake(..) results in a different outcome than running it through subprocess.Popen(...,shell=True)

Full example demonstrating the issue on https://pastebin.com/nzh5WmkX

**Comment by michael-will** [comment]
Output of the code above:

baking
executing
waiting
sending incremental file list
.foo
dontignoreme.arb
ignoreme
ignoreme.arb.$temp
ignoreme.arb.someshit
subdir/
subdir/dontignoremeeither.arb

sent 515 bytes  received 142 bytes  1,314.00 bytes/sec
total size is 0  speedup is 0.00

done pass 1
prepared cmd_string: /usr/bin/rsync -rptlog --size-only -av --include='*/' --include='**/*.arb' --exclude='*' src/ dest2/
executing
waiting
sending incremental file list
dontignoreme.arb
subdir/
subdir/dontignoremeeither.arb

sent 266 bytes  received 66 bytes  664.00 bytes/sec
total size is 0  speedup is 0.00
done

**Comment by ratman** [comment]
I can confirm the same.

**Comment by amoffat** [comment]
```python
import sh
rsync = sh.rsync.bake("-rptlog", "--size-only", "-ansv", "--include=*/", "--include=**/*.arb", "--exclude=*")
rsync("src/", "dest/")
```

```
sending incremental file list
./
dontignoreme.arb
dontignoremeeither.arb

sent 126 bytes  received 25 bytes  302.00 bytes/sec
total size is 0  speedup is 0.00 (DRY RUN)
```

Notice how I remove the quotes around the `--include` and `--exclude` values.  The quotes are only necessary when you're passing those options in the *shell* (which you're doing with `subprocess.Popen(shell=True)`).  This keeps the shell from expanding `*`, so that rsync receives, for example, `--exclude=*` instead of `--exclude=file1 file2 file3 file4...`.

The quotes aren't needed in sh, since we don't launch through a shell, and so quoted args are the source of the issue.
