### ISSUE TITLE
Allow exception truncation to print head, tail, or head+tail for long output

### ISSUE THREAD

**Issue by alex-dr** [amoffat/sh#471]
I have a ton of cases where we have a long-running command with lots of output, and our exception messages from sh only show the head of the output. Typically the interesting stuff in a failure is in the tail of the output.

Obviously we don't want to change the default behavior, but a kwarg to enable tail output in exception messages (and specify length) would be awesome.

**Comment by amoffat** [comment]
I take your point about the interesting stuff being in the bottom of the log, and I appreciate you considering not changing default behavior. I think since you are the first person to request this, it is a little too specific to warrant an option. My suggestion would be to catch the sh exception at a high level and render `e.stderr` or `e.stdout` in the way you see fit.
