### ISSUE TITLE
Subprocess not been killed when main python script got SIGINT

### ISSUE THREAD

**Issue by lzw19951010** [amoffat/sh#495]
```
# debug.sh
while true
do
    echo "hello" >> tmp
done
```

```
# this script cannot kill "debug.sh" after SIGINT(ctrl-c)
import sh
import os
cmd_ttr=os.path.join("/home/","debug.sh")
cmd=sh.Command("bash")
ret=cmd("debug.sh")
```

```
# but this script can kill "debug.sh" after SIGINT(ctrl-c)
import sh
import os
cmd_ttr=os.path.join("/home/","debug.sh")
cmd=sh.Command("bash")
ret=cmd("debug.sh", _fg=True)
```
I am new to sh, it would be great if someone introduce the proper way to kill all the subprocesses launched by a python script.

**Comment by amoffat** [comment]
The reason why the second one works is because `bash debug.sh` is launched in the foreground process group, in the same process group and session as the python process, so ctrl-c sent from your terminal is received by both `debug.sh` and python.

The first one doesn't work because a process launched with sh will go in its own process session, because [`_new_session=True`](http://amoffat.github.io/sh/sections/special_arguments.html?highlight=foreground#new-session), where it becomes the session leader and group leader.  It's essentially not connected to your terminal in any way.  It's up to you to send signals to it.

If you want to terminate a process launched in this way, you need to run it in the background and you need to catch `KeyboardInterrupt` and send your subprocess a signal directly.  Pseudo-code (untested):

```python
process = cmd("debug.sh", _bg=True)
try:
    process.wait()
except KeyboardInterrupt:
    procecss.kill()
```

**Comment by lzw19951010** [comment]
Thank you. That's a detailed explanation. But I'm still curious about the default `_new_session=True` setting. Because I thought it's quite natural to terminate all the subprocesses after I send SIGINT, it would be very helpful if you can enlighten me on this.

**Comment by amoffat** [comment]
You're right, I agree it does seem like it could be more natural to terminate all the child processes. 
 Looking at the source code though, it looks like I ensure that either the launched subprocess is in a new session (if _new_session=True) or in a new process group.  So it is clear that I thought the launched subprocess should be insulated from its parent's group signals.  I'll need to think a little more to try to remember the reason.

One way to look at it might be: sending SIGINT to a process and expecting it to be delivered to all of the children processes implies that all of the child processes are related (and must be in the same foreground process group).  This can be true with some python scripts using sh to launch some background helper processes.  It can also be not true, in the case where your python script is used as a system script to start up a bunch of long-running background jobs.  Then if you sent SIGINT, you may be surprised to see all of the background jobs terminate as well. 

You could make the argument that if a process is launched with `_bg=True`, that it should automatically go into a new session or new group, otherwise not.  That might be more correct behavior.  What are your thoughts?

**Comment by lzw19951010** [comment]
Background job is a good example, but based on my experience using scripts to controll workflow/service, I think in this case, the caller should be explicitly launch these process with `_bg=True`.
and that process should be automatically go into a new session.

**Comment by gergelyhunyady** [comment]
I also bumped into this. I think it would make sense to align this behavior with the standard subprocess lib behavior, where the default case is that ^C interrupts subprocesses as well.

**Comment by EricCousineau-TRI** [comment]
Not a user of `sh`, but came across while trying to figger this out myself. I expanded on Andrew's example above and wrote something like this (this is only based on stdlib):
https://gist.github.com/EricCousineau-TRI/e042efcfbb27fa971efd86e496ceab8d

I assume it'd be similar if you replace `Popen(...)` with `cmd(..., _bg=True)`.

**Comment by amoffat** [comment]
2.0.0 has a [new process launching defaults](https://github.com/amoffat/sh/blob/develop/MIGRATION.md#new-processes-dont-launch-in-new-session) that make more sense and address the original issue
