### ISSUE TITLE
os.fork() --> RuntimeError: fork not supported for subinterpreters

### ISSUE THREAD

**Issue by bwakkie** [amoffat/sh#534]
From python 3.8 (standard in Ubuntu 20.04 now) I am getting runtime errors from the os.fork() (line 1978) command used in sh.py when running via mod_wsgi.
I am not sure how to move on or if it is a bug within that app i am using.
Is there a replacement functiin to be used now?
I am using sh.py 1.13.1 and python 3.8.2
https://docs.python.org/3/library/os.html#os.fork

**Comment by bwakkie** [comment]
https://docs.python.org/3/library/os.html#os.fork

**Comment by ecederstrand** [comment]
Can you please post the full stack trace?

**Comment by bwakkie** [comment]
Here is the error I got https://gitlab.com/mayan-edms/mayan-edms/-/issues/845

**Comment by ecederstrand** [comment]
Looks like a bug in Python 3.8 (https://bugs.python.org/issue37951) that was fixed before Python 3.8.0. Are you sure the Python that produced the stack trace is actually version 3.8.2?

Since this happened through mod_wsgi, there is supposed to be a workaround in FreeIPA (which is used by mod_wsgi) to address this: https://github.com/freeipa/freeipa/commit/3fbd0abf253c4d46134820337269008bfa2a7240. It is available in at least FreeIPA 4.8.8.

Anyway, this looks like an error in the way `sh` is initialized by the calling code. I don't think it's a bug with `sh` as such.

**Comment by ecederstrand** [comment]
Actually, scratch that.

`mod_wsgi` runs applications in sub interpreters: https://modwsgi.readthedocs.io/en/develop/user-guides/processes-and-threading.html#python-sub-interpreters

`sh` uses `os.fork()` to launch processes: https://amoffat.github.io/sh/sections/architecture.html#launch

And forking in a sub interpreter is no longer supported in Python 3.8: https://docs.python.org/3/library/os.html#os.fork

I don't think there's anything `sh` can do to fix this.

Possible workarounds are:

1. Replace `mod_wsgi` with a different app server that does not run processes in a sub interpreter
1. Downgrade Python to a version that does not impose this restriction

**Comment by ecederstrand** [comment]
I'm closing this issue because I don't think there's anything we can do in `sh` to fix this. Feel free to reopen if you disagree.
