### ISSUE TITLE
How to "_iter" over stdout and sterr?

### ISSUE THREAD

**Issue by halloleo** [amoffat/sh#550]
I have a long running command which on `stdout` outputs some normal progress information (with line overwrite escape sequences to not clutter the screen), on `stderr` it outputs the internal exceptions it catches on the way.

I use a construct like

```
    for out_chunk in long_running_command(*args, _iter=True, _out_bufsize=0):
        sys.stdout.write(out_chunk)
```

to get the progress nicely reported, but the exception messages from `stderr` are all gobbled up and never shown.

How can I output both, `stdout` and `sterr`? `_iter` seems to support only either-or.

**Comment by ecederstrand** [comment]
You cannot access STDERR and STDOUT separately when iterating (i.e. `for out_chunk, err_chunk in long_running_command(...):` is not possible) but you can redirect SDTERR to STDOUT with the [_err_to_out](http://amoffat.github.io/sh/sections/special_arguments.html#err-to-out) kwarg.

**Comment by halloleo** [comment]
Thanks @ecederstrand. Iterating over them separately would be the best, but redirecting is certainly a option for me. 

Do you want to keep the issue open? I'm happy to close it for my use case.

**Comment by ecederstrand** [comment]
Let’s keep it open. @amoffat marked it as a possible improvement for sh 2.0.0.

**Comment by amoffat** [comment]
The bad news is that I took a look at what it would take to implement this, and it would be very complicated. The good news (although I didn't think of it at the time this issue was created) is that it is possible to have asynchronous access to both stdout and stderr separately, just not while using the `_iter` special kwarg. I've added a test showing how to do it https://github.com/amoffat/sh/commit/2cb2195906ca1147b7611b3c463303428fedc421

If you really wanted to, you could write some generator wrapper that yields items from the `out` and `err` lists as they become available, and then you'll have a single iterable that you can use in the main thread.
