### ISSUE TITLE
Need way to pass sh.Command instances into baked commands

### ISSUE THREAD

**Issue by nolanl** [amoffat/sh#554]
At least the naive way doesn't work:
```
fakeroot = sh.fakeroot.bake('-i', 'fr.db', '-s', 'fr.db')
dothing = sh.Command('/path/to/nonpath/script')
fakeroot.dothing('arg')
```
this expands out to:
```
/usr/bin/fakeroot -i fr.db -s fr.db dothing arg
```
which of course doesn't work, because dothing is not in the path. I assume the baked fakeroot only checks for files in $PATH, and not for an instance of sh.Command in the local scope?

I can, of course, just skip the baked fakeroot in this case, but it would be nice to not have that duplication...

**Comment by amoffat** [comment]
`fakeroot.dothing('arg')` doesn't actually look in your $PATH at all for `dothing`. The dot syntax is a convenience syntax for passing arguments to commands, so it can be rewritten as `fakeroot('dothing', 'arg')`.

There is nothing smart that sh can do here because in some programs, like git, the subcommand is not an executable on the system (ie `git.log()`), whereas in examples like yours, it is an executable.

**Comment by nolanl** [comment]
Thanks, for the explanation, that makes sense.
