### ISSUE TITLE
Explanation of what makes an arg globbing and what doesn't?

### ISSUE THREAD

**Issue by jerkstorecaller** [amoffat/sh#557]
First, thanks for this wonderful library.

I went through the manual, and there's one thing I don't get. In this FAQ https://amoffat.github.io/sh/sections/faq.html#why-doesn-t-work-as-a-command-argument , it says "in order to use * like you would on the commandline, pass it into glob.glob() first".

I was curious about this, and ran a couple of tests.

```
#Doesn't work, as doc says
sh.ls("*.py")

#Works, as doc says
sh.ls(glob.glob("*.py"))

#Works despite not being globbed 
sh.find(".", "-name", "*.py")
```

I'd like to understand why the find command didn't need globbing.

**Comment by ecederstrand** [comment]
This is how globbing in the shell works. It's not something unique to `sh`.

If you run `find . -name *.py` in a folder with more than one .py file, then you will get an error:

```bash
$ ls *.py
scratch.py	scratch2.py	scratch3.py
$ find ./ -name '*.py'
scratch.py
scratch2.py
scratch3.py
$ find ./ -name *.py
find: scratch2.py: unknown primary or operator
```

This is because your shell substitutes `*.py` with `scratch.py scratch2.py scratch3.py` before `find` is executed. If you want to use a globbing pattern with find, you have to put the pattern in quotes.

**Comment by jerkstorecaller** [comment]
I see. Thanks for the explanation.
