### ISSUE TITLE
Tags for 2.0.0 & 2.0.1?

### ISSUE THREAD

**Issue by jakirkham** [amoffat/sh#646]
It looks like 2.0.0 & 2.0.1 were released recently. Congratulations! 🎉

Would it be possible to add tags for these releases? This would help when trying to understand the changes that have occurred since the last 1.x release 🙂

**Comment by amoffatgmi** [comment]
Done. Do you know how to do this automatically with Github Actions as part of a merge to the main branch?

**Comment by ecederstrand** [comment]
There's a GitHub action for tagging on pushes to the master branch: https://github.com/marketplace/actions/github-tag As input we can just extract the version number from the package.

If we want to be even more automatic, there's https://www.conventionalcommits.org/ and tools that can calculate the next version number based on the type of commits since the last version bump.
